/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.util.concurrent.Semaphore;

/**
 *
 * @author sebas
 */
public class VentanaFabrica extends javax.swing.JFrame {
    archivoCsv archivo = new archivoCsv();
    int dia;
    int dias;
    int empleados = 15;
    String cadena = "";
    Cola colaLibrePantalla = new Cola();
    Cola ColaOcupadoPantalla = new Cola();
    Cola colaLibreBotones = new Cola();
    Cola colaOcupadoBotones = new Cola();
    Cola colaLibrePinesC = new Cola();
    Cola colaOcupadoPinesC = new Cola();
    Cola colaLibreCamaras = new Cola();
    Cola colaOcupadoCamaras = new Cola();
    Cola colaEnsambladoresLibres = new Cola();
    Cola colaEnsambladoresOcupados = new Cola();
    Semaphore sem = new Semaphore(1);
    Semaphore sem2 = new Semaphore(1);
    Semaphore sem3 = new Semaphore(1);
    Semaphore sem4 = new Semaphore(1);
    Semaphore almacenPantallas;
    Semaphore almacenBotones;
    Semaphore almacenPinesC;
    Semaphore almacenCamaras;

    /**
     * Creates new form VentanaFabrica
     */
    public VentanaFabrica() {
        initComponents();
//        archivo.escribirCvsPorDefecto(cadena);
        archivo.leerPorDefecto(dia, dias, fab2aC, fab2aC1, fab2aC2, fab2aC3);
        almacenPantallas = new Semaphore(Integer.parseInt(fab2aC.getText()));
        almacenBotones = new Semaphore(Integer.parseInt(fab2aC1.getText()));
        almacenPinesC = new Semaphore(Integer.parseInt(fab2aC2.getText()));
        almacenCamaras = new Semaphore(Integer.parseInt(fab2aC3.getText()));
        
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Fabrica");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        Fab2B = new javax.swing.JLabel();
        Fab2C = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Fab2Pc = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        Fab2P = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Fab2PA = new javax.swing.JLabel();
        Fab2BA = new javax.swing.JLabel();
        Fab2PcA = new javax.swing.JLabel();
        Fab2CA = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fab2aC = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        fab2aC1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        fab2aC2 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        fab2aC3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Productores");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setText("Pantallas");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel4.setText("Fabrica 1 ");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel5.setText("Pin de carga");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel6.setText("Camara");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel8.setText("Botones");
        Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel9.setText("Almacenes (Cantidad)");
        Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 50, 30));

        jLabel11.setText("0");
        Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 20, 20));

        jLabel12.setText("0");
        Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 20, -1));

        jLabel13.setText("0");
        Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 20, -1));

        jLabel14.setText("0");
        Panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 20, -1));

        jButton2.setText("+");
        Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 50, 30));

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 50, 30));

        jButton4.setText("+");
        Panel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 50, 30));

        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Panel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 50, 30));

        jButton6.setText("+");
        Panel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 50, 30));

        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Panel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 50, 30));

        jButton8.setText("+");
        Panel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 50, 30));

        jLabel15.setText("0");
        Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 20, -1));

        jLabel16.setText("0");
        Panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 20, 20));

        jLabel17.setText("0");
        Panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 20, -1));

        jLabel18.setText("0");
        Panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 20, -1));

        jLabel19.setText("0");
        Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 20, -1));

        jLabel20.setText("0");
        Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 20, 20));

        jLabel21.setText("0");
        Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 20, -1));

        jLabel22.setText("0");
        Panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 20, -1));

        jLabel10.setText("Ensambladores");
        Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel23.setText("0");
        Panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 20, -1));

        jButton9.setText("+");
        Panel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 50, 30));

        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Panel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 50, 30));

        jLabel25.setText("0");
        Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 20, -1));

        jLabel26.setText("Xperia 1 IV (Producidos)");
        Panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel24.setText("Productores");
        Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel27.setText("Pantallas");
        Panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel29.setText("Pin de carga");
        Panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        jLabel30.setText("Camara");
        Panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jLabel31.setText("Botones");
        Panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jLabel32.setText("Almacenes (Cantidad)");
        Panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, -1, -1));

        jButton11.setText("-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Panel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 50, 30));

        Fab2B.setText("0");
        Panel.add(Fab2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 20, 20));

        Fab2C.setText("0");
        Panel.add(Fab2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 20, -1));

        jLabel35.setText("0");
        Panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 20, -1));

        Fab2Pc.setText("0");
        Panel.add(Fab2Pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 20, -1));

        jButton12.setText("+");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Panel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 50, 30));

        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Panel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 50, 30));

        jButton14.setText("+");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Panel.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 50, 30));

        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        Panel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 50, 30));

        jButton16.setText("+");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Panel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 50, 30));

        jButton17.setText("-");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        Panel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 50, 30));

        jButton18.setText("+");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        Panel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 50, 30));

        Fab2P.setText("0");
        Panel.add(Fab2P, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 20, -1));
        Panel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 20, -1));

        Fab2PA.setText("0");
        Panel.add(Fab2PA, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 30, 20));

        Fab2BA.setText("0");
        Panel.add(Fab2BA, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 30, 20));

        Fab2PcA.setText("0");
        Panel.add(Fab2PcA, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 30, 20));

        Fab2CA.setText("0");
        Panel.add(Fab2CA, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 30, 20));

        jLabel45.setText("Ensambladores");
        Panel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jButton19.setText("+");
        Panel.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 50, 30));

        jButton20.setText("-");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        Panel.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 50, 30));

        jLabel47.setText("0");
        Panel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 20, -1));

        jLabel48.setText("Xperia 10 IV (Producidos)");
        Panel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));

        jLabel49.setText("Gerente esta...");
        Panel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel50.setText("Jefe esta... ");
        Panel.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel51.setText("Fabrica 2");
        Panel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel28.setText("null");
        Panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel54.setText("null");
        Panel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel52.setText("Gerente esta...");
        Panel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jLabel53.setText("Jefe esta... ");
        Panel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel55.setText("null");
        Panel.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        jLabel56.setText("null");
        Panel.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jLabel57.setText("HORA");
        Panel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel1.setText("jLabel1");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -20, 210, 180));

        jButton21.setText("Iniciar Fabricas");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        Panel.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel7.setText(" /");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 20, 20));

        fab2aC.setText("40");
        Panel.add(fab2aC, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 30, 20));

        jLabel33.setText(" /");
        Panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 20, 20));

        fab2aC1.setText("45");
        Panel.add(fab2aC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 30, 20));

        jLabel34.setText(" /");
        Panel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 20, 20));

        fab2aC2.setText("15");
        Panel.add(fab2aC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 30, 20));

        jLabel36.setText(" /");
        Panel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 20, 20));

        fab2aC3.setText("20");
        Panel.add(fab2aC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 40, 20));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -10, 860, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if ( !ColaOcupadoPantalla.esta_vacia()) {
        Procesos siguiente = ColaOcupadoPantalla.getPfirst().getproceso();
        ColaOcupadoPantalla.Desencolar();
        colaLibrePantalla.Encolar(siguiente);
        siguiente.suspend();
        Fab2P.setText(Integer.toString(Integer.parseInt(Fab2P.getText())-1));
        empleados++;
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if ( !colaOcupadoBotones.esta_vacia()) {
        Procesos siguiente = colaOcupadoBotones.getPfirst().getproceso();
        colaOcupadoBotones.Desencolar();
        colaLibreBotones.Encolar(siguiente);
        siguiente.suspend();
        Fab2B.setText(Integer.toString(Integer.parseInt(Fab2B.getText())-1));
        empleados++;
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if ( !colaOcupadoPinesC.esta_vacia()) {
        Procesos siguiente = colaOcupadoPinesC.getPfirst().getproceso();
        colaOcupadoPinesC.Desencolar();
        colaLibrePinesC.Encolar(siguiente);
        siguiente.suspend();
        Fab2Pc.setText(Integer.toString(Integer.parseInt(Fab2Pc.getText())-1));
        empleados++;
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if ( !colaOcupadoCamaras.esta_vacia()) {
        Procesos siguiente = colaOcupadoCamaras.getPfirst().getproceso();
        colaOcupadoCamaras.Desencolar();
        colaLibreCamaras.Encolar(siguiente);
        siguiente.suspend();
        Fab2C.setText(Integer.toString(Integer.parseInt(Fab2C.getText())-1));
        empleados++;
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Productores productores = new Productores();
        productores.agregarProductores(Fab2PA,colaLibrePantalla,sem,almacenPantallas,Fab2BA,colaLibreBotones,sem2,almacenBotones,Fab2PcA,colaLibrePinesC,sem3,almacenPinesC,Fab2CA,colaLibreCamaras,sem4,almacenCamaras);
        empleados = archivo.leerPorDefecto2(empleados,colaLibrePantalla,ColaOcupadoPantalla,colaLibreBotones,colaOcupadoBotones,colaLibrePinesC,colaOcupadoPinesC,colaLibreCamaras,colaOcupadoCamaras,Fab2P,Fab2B,Fab2Pc,Fab2C);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (empleados!=0) {
        Procesos siguiente = colaLibrePantalla.getPfirst().getproceso();
        colaLibrePantalla.Desencolar();
        ColaOcupadoPantalla.Encolar(siguiente);
         if (siguiente.getState() != Thread.State.NEW) {
                siguiente.resume();
            }else{
        siguiente.start();
         }
        Fab2P.setText(Integer.toString(Integer.parseInt(Fab2P.getText())+1));
        empleados--;
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
         if (empleados>0) {
            Procesos siguiente = colaLibreBotones.pfirst.getproceso();
            colaLibreBotones.Desencolar();
            colaOcupadoBotones.Encolar(siguiente);
            if (siguiente.getState() != Thread.State.NEW) {
                siguiente.resume();
                }else{
            siguiente.start();
             }
        Fab2B.setText(Integer.toString(Integer.parseInt(Fab2B.getText())+1));
        empleados--;
            
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
         if (empleados!=0) {
        Procesos siguiente = colaLibrePinesC.getPfirst().getproceso();
        colaLibrePinesC.Desencolar();
        colaOcupadoPinesC.Encolar(siguiente);
         if (siguiente.getState() != Thread.State.NEW) {
                siguiente.resume();
            }else{
        siguiente.start();
         }
        Fab2Pc.setText(Integer.toString(Integer.parseInt(Fab2Pc.getText())+1));
        empleados--;
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (empleados!=0) {
        Procesos siguiente = colaLibreCamaras.getPfirst().getproceso();
        colaLibreCamaras.Desencolar();
        colaOcupadoCamaras.Encolar(siguiente);
         if (siguiente.getState() != Thread.State.NEW) {
                siguiente.resume();
            }else{
        siguiente.start();
         }
        Fab2C.setText(Integer.toString(Integer.parseInt(Fab2C.getText())+1));
        empleados--;
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFabrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fab2B;
    private javax.swing.JLabel Fab2BA;
    private javax.swing.JLabel Fab2C;
    private javax.swing.JLabel Fab2CA;
    private javax.swing.JLabel Fab2P;
    private javax.swing.JLabel Fab2PA;
    private javax.swing.JLabel Fab2Pc;
    private javax.swing.JLabel Fab2PcA;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel fab2aC;
    private javax.swing.JLabel fab2aC1;
    private javax.swing.JLabel fab2aC2;
    private javax.swing.JLabel fab2aC3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
