/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.util.concurrent.Semaphore;
import javax.swing.JLabel;

/**
 *
 * @author sebas
 */
public class VentanaFabrica extends javax.swing.JFrame {
    archivoCsv archivo = new archivoCsv();
    long dia=0;
    int dias;
    int empleados = 15;
    String cadena = "";
    Cola colaLibrePantalla = new Cola();
    Cola ColaOcupadoPantalla = new Cola();
    Cola colaLibreBotones = new Cola();
    Cola colaOcupadoBotones = new Cola();
    Cola colaLibrePinesC = new Cola();
    Cola colaOcupadoPinesC = new Cola();
    Cola colaLibreCamaras = new Cola();
    Cola colaOcupadoCamaras = new Cola();
    Cola colaEnsambladoresLibres = new Cola();
    Cola colaEnsambladoresOcupados = new Cola();
    Semaphore sem = new Semaphore(1);
    Semaphore sem2 = new Semaphore(1);
    Semaphore sem3 = new Semaphore(1);
    Semaphore sem4 = new Semaphore(1);
    Semaphore mutex = new Semaphore(1);
    Semaphore mutex2 = new Semaphore(1);
    Semaphore mutex3 = new Semaphore(1);
    Semaphore mutex4 = new Semaphore(1);
    Semaphore almacenPantallas;
    Semaphore almacenBotones;
    Semaphore almacenPinesC;
    Semaphore almacenCamaras;
    Semaphore p = new Semaphore(1);
    Semaphore B= new Semaphore(1);
    Semaphore Pc= new Semaphore(1);
    Semaphore C= new Semaphore(1);
    Semaphore modCountdown = new Semaphore(1);
    public void agregar(int tipo,Cola libre,Cola ocupada,JLabel trabajador){
        if (empleados!=0) {
            if (tipo==1) {
                Procesos hiloP = new Procesos(tipo, Fab2PA, sem, almacenPantallas, dia, p,Countdown);
                ocupada.Encolar(hiloP);
                hiloP.start();
            }if (tipo==2) {
                Procesos hiloB = new Procesos(tipo, sem2, almacenBotones, Fab2BA, dia, B,Countdown);
                ocupada.Encolar(hiloB);
                hiloB.start();
            }if (tipo==3) {
                Procesos hiloPc = new Procesos(tipo, sem3, Fab2PcA, almacenPinesC, dia, Pc,Countdown);
                ocupada.Encolar(hiloPc);
                hiloPc.start();
            }if (tipo==4) {
                Procesos hiloC = new Procesos(Fab2CA, tipo, sem4, almacenCamaras, dia, C,Countdown);
                ocupada.Encolar(hiloC);
                hiloC.start();
            }if (tipo==5) {
                Procesos hiloE = new Procesos(mutex4, mutex3, mutex2, mutex, dia, tipo, sem, sem2, sem3, sem4, Fab2PA, Fab2BA, Fab2PcA, Fab2CA, Fab2E, Fab2TA, almacenPantallas, almacenBotones, almacenPinesC, almacenCamaras,Countdown);
                ocupada.Encolar(hiloE);
                hiloE.start();
            }
        trabajador.setText(Integer.toString(Integer.parseInt(trabajador.getText())+1));
        empleados--;
        }
    }
    public void quitar(Cola ocupado,Cola libre,JLabel trabajadores,Semaphore mutexq,Semaphore semq){
        if ( !ocupado.esta_vacia()) {
        Procesos siguiente = ocupado.getPfirst().getproceso();
        ocupado.Desencolar();
        libre.Encolar(siguiente);
        mutexq.release();
        semq.release();
        siguiente.suspend();
        trabajadores.setText(Integer.toString(Integer.parseInt(trabajadores.getText())-1));
        empleados++;
        }
    }

    /**
     * Creates new form VentanaFabrica
     */
    public VentanaFabrica() {
        initComponents();
//        archivo.escribirCvsPorDefecto(cadena);
        dia = archivo.leerPorDefecto(dia, dias, fab2aC, fab2aC1, fab2aC2, fab2aC3);
        almacenPantallas = new Semaphore(Integer.parseInt(fab2aC.getText()));
        almacenBotones = new Semaphore(Integer.parseInt(fab2aC1.getText()));
        almacenPinesC = new Semaphore(Integer.parseInt(fab2aC2.getText()));
        almacenCamaras = new Semaphore(Integer.parseInt(fab2aC3.getText()));
        Countdown.setText(Integer.toString(dias));
        
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Fabrica");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Fab2E = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Sueldoe = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        Fab2B = new javax.swing.JLabel();
        Fab2C = new javax.swing.JLabel();
        Fab2Pc = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        Fab2P = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        Fab2TA = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        acciong = new javax.swing.JLabel();
        accion = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        Countdown = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        Sueldop2 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fab2aC1 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        Sueldop1 = new javax.swing.JLabel();
        Fab2BA = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        Sueldoc = new javax.swing.JLabel();
        Fab2PA = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        fab2aC2 = new javax.swing.JLabel();
        Fab2PcA = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        fab2aC3 = new javax.swing.JLabel();
        Fab2CA = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        fab2aC = new javax.swing.JLabel();
        Sueldop = new javax.swing.JLabel();
        Sueldob = new javax.swing.JLabel();
        Sueldopc = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Componente");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel3.setText("Pantalla(s)");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel4.setText("Fabrica 1 ");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel5.setText("0");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 10, -1));

        Fab2E.setText("0");
        Panel.add(Fab2E, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel9.setText("Unidades ");
        Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 40, 30));

        Sueldoe.setText("0");
        Panel.add(Sueldoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 30, -1));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 40, 30));

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 40, 30));

        jButton4.setText("+");
        Panel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 40, 30));

        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Panel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 40, 30));

        jButton6.setText("+");
        Panel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 40, 30));

        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Panel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 40, 30));

        jButton8.setText("+");
        Panel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 40, 30));

        jLabel19.setText("45");
        Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 20, -1));

        jLabel10.setText("Ensambladores");
        Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jButton9.setText("+");
        Panel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 40, 30));

        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Panel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 40, 30));

        jLabel25.setText("0");
        Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 20, -1));

        jLabel26.setText("Xperia 1 IV (Producidos)");
        Panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 140, -1));

        jLabel24.setText("Productores");
        Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel32.setText("Sueldo");
        Panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, -1));

        jButton11.setText("-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Panel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 40, 30));

        Fab2B.setText("0");
        Panel.add(Fab2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 20, 20));

        Fab2C.setText("0");
        Panel.add(Fab2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 20, -1));

        Fab2Pc.setText("0");
        Panel.add(Fab2Pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 20, -1));

        jButton12.setText("+");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Panel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 40, 30));

        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Panel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 40, 30));

        jButton14.setText("+");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Panel.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 40, 30));

        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        Panel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 40, 30));

        jButton16.setText("+");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Panel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 40, 30));

        jButton17.setText("-");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        Panel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 40, 30));

        jButton18.setText("+");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        Panel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 40, 30));

        Fab2P.setText("0");
        Panel.add(Fab2P, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 20, -1));
        Panel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 20, -1));

        jButton19.setText("+");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        Panel.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 40, 30));

        jButton20.setText("-");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        Panel.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 40, 30));

        Fab2TA.setText("0");
        Panel.add(Fab2TA, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 40, 20));

        jLabel48.setText("Xperia 10 IV (Producidos)");
        Panel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        jLabel49.setText("Gerente esta...");
        Panel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel50.setText("Jefe esta... ");
        Panel.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel51.setText("Fabrica 2");
        Panel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel28.setText("null");
        Panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel54.setText("0");
        Panel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        acciong.setText("null");
        Panel.add(acciong, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        accion.setText("null");
        Panel.add(accion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel57.setText("HORA");
        Panel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jButton21.setText("Iniciar Fabricas");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        Panel.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel35.setText("Dias:");
        Panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        Countdown.setText("0");
        Panel.add(Countdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 50, -1));

        jLabel38.setText("Productores");
        Panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel58.setText("Botones");
        Panel.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel59.setText("0");
        Panel.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel8.setText("Pin(es) de carga");
        Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, -1));

        jLabel11.setText("Pin(es) de carga");
        Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, -1));

        jLabel14.setText("Pin(es) de carga");
        Panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, -1));

        jLabel15.setText("Camara(s)");
        Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel20.setText("0");
        Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 20, -1));

        jLabel21.setText("0");
        Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 20, -1));

        jLabel22.setText("/");
        Panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 20, -1));

        jLabel23.setText("0");
        Panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 20, -1));

        jLabel27.setText("0");
        Panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 20, -1));

        jLabel29.setText("/");
        Panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 20, -1));

        jLabel30.setText("15");
        Panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 20, -1));

        jLabel31.setText("0");
        Panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 20, -1));

        jLabel40.setText("/");
        Panel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 20, -1));

        jLabel41.setText("20");
        Panel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 20, -1));

        jLabel42.setText("0");
        Panel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 20, -1));

        jLabel43.setText("/");
        Panel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 20, -1));

        jLabel55.setText("null");
        Panel.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        Sueldop2.setText("0");
        Panel.add(Sueldop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 20, -1));

        jLabel44.setText("40");
        Panel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 20, -1));

        jLabel46.setText("0");
        Panel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 20, -1));

        jLabel47.setText("0");
        Panel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 20, -1));

        jLabel52.setText("0");
        Panel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 20, -1));

        jLabel12.setText("Unidades ");
        Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        fab2aC1.setText("45");
        Panel.add(fab2aC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 20, -1));

        jLabel60.setText("Sueldo");
        Panel.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 40, -1));

        Sueldop1.setText("0");
        Panel.add(Sueldop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 20, -1));

        Fab2BA.setText("0");
        Panel.add(Fab2BA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 20, -1));

        jLabel63.setText("/");
        Panel.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 20, -1));

        Sueldoc.setText("0");
        Panel.add(Sueldoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 30, -1));

        Fab2PA.setText("0");
        Panel.add(Fab2PA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 20, -1));

        jLabel66.setText("/");
        Panel.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 20, -1));

        fab2aC2.setText("15");
        Panel.add(fab2aC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 20, -1));

        Fab2PcA.setText("0");
        Panel.add(Fab2PcA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 20, -1));

        jLabel69.setText("/");
        Panel.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 20, -1));

        fab2aC3.setText("20");
        Panel.add(fab2aC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 20, -1));

        Fab2CA.setText("0");
        Panel.add(Fab2CA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 20, -1));

        jLabel72.setText("/");
        Panel.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 20, -1));

        jLabel73.setText("0");
        Panel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        fab2aC.setText("40");
        Panel.add(fab2aC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 20, -1));

        Sueldop.setText("0");
        Panel.add(Sueldop, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 30, -1));

        Sueldob.setText("0");
        Panel.add(Sueldob, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 30, -1));

        Sueldopc.setText("0");
        Panel.add(Sueldopc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 30, -1));

        jLabel16.setText("Ensambladores");
        Panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        jLabel7.setText("0");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel33.setText("0");
        Panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 20, -1));

        jLabel17.setText("0");
        Panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 20, -1));

        jLabel6.setText("Fabrica 2");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        jLabel13.setText("Fabrica 1");
        Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        quitar(ColaOcupadoPantalla, colaLibrePantalla, Fab2P, sem, p);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        quitar(colaOcupadoBotones, colaOcupadoBotones, Fab2B, B, sem2);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        quitar(colaOcupadoPinesC, colaLibrePinesC, Fab2Pc, Pc, sem3);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        quitar(colaOcupadoCamaras, colaLibreCamaras, Fab2C, C, sem4);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
         if ( !colaEnsambladoresOcupados.esta_vacia()) {
        Procesos siguiente = colaEnsambladoresOcupados.getPfirst().getproceso();
        colaEnsambladoresOcupados.Desencolar();
        siguiente.suspend();
        siguiente.sem.release();
        siguiente.sem2.release();
        siguiente.sem3.release();;
        siguiente.sem4.release();
        Fab2E.setText(Integer.toString(Integer.parseInt(Fab2E.getText())-1));
        empleados++;
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Countdown.setText("30");
        empleados = archivo.leerPorDefecto2(dia,empleados,colaLibrePantalla,ColaOcupadoPantalla,colaLibreBotones,colaOcupadoBotones,colaLibrePinesC,colaOcupadoPinesC,colaLibreCamaras,colaOcupadoCamaras,Fab2P,Fab2B,Fab2Pc,Fab2C,colaEnsambladoresLibres,colaEnsambladoresOcupados,Fab2E,Fab2PA,Fab2BA,Fab2PcA,Fab2CA,Fab2TA,sem,sem2,sem3,sem4,almacenPantallas,almacenBotones,almacenPinesC,almacenCamaras,p,B,Pc,C,mutex4,mutex3,mutex2,mutex,Countdown);
        Procesos pagos = new Procesos(Fab2P, Fab2B, Fab2Pc, Fab2C, Sueldop, Sueldob, Sueldopc, Sueldoc,Fab2E,Sueldoe,0,dia,Sueldop2,Sueldop1,Countdown);
        pagos.start();
        ProcesosJG jefe = new ProcesosJG(1,dia,modCountdown, Countdown, accion);
        jefe.start();
        ProcesosJG gerente = new ProcesosJG(dia, 3, modCountdown, acciong, Countdown,Fab2TA,accion,Sueldop2);
        gerente.start();
        ProcesosJG dias = new ProcesosJG(dia, Countdown, 2);
        dias.start();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        agregar(1,colaLibrePantalla, ColaOcupadoPantalla, Fab2P);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
         agregar(2,colaLibreBotones, colaOcupadoBotones, Fab2B);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        agregar(3,colaLibrePinesC, colaOcupadoPinesC, Fab2Pc);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        agregar(4,colaLibreCamaras, colaOcupadoCamaras, Fab2C);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        agregar(5,colaEnsambladoresLibres, colaEnsambladoresOcupados, Fab2E);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFabrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Countdown;
    private javax.swing.JLabel Fab2B;
    private javax.swing.JLabel Fab2BA;
    private javax.swing.JLabel Fab2C;
    private javax.swing.JLabel Fab2CA;
    private javax.swing.JLabel Fab2E;
    private javax.swing.JLabel Fab2P;
    private javax.swing.JLabel Fab2PA;
    private javax.swing.JLabel Fab2Pc;
    private javax.swing.JLabel Fab2PcA;
    private javax.swing.JLabel Fab2TA;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Sueldob;
    private javax.swing.JLabel Sueldoc;
    private javax.swing.JLabel Sueldoe;
    private javax.swing.JLabel Sueldop;
    private javax.swing.JLabel Sueldop1;
    private javax.swing.JLabel Sueldop2;
    private javax.swing.JLabel Sueldopc;
    private javax.swing.JLabel accion;
    private javax.swing.JLabel acciong;
    private javax.swing.JLabel fab2aC;
    private javax.swing.JLabel fab2aC1;
    private javax.swing.JLabel fab2aC2;
    private javax.swing.JLabel fab2aC3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
